version: '3.8'

services:
  api:
    container_name: wshop_api_store
    build:
      context: ./docker
      dockerfile: ./Dockerfile
    ports:
      - ${API_PORT}:80
    volumes:
      - ./wshop-api-store:/var/www/wshop-api-store
    working_dir: /var/www/wshop-api-store
    networks:
      - api_network

networks:
  api_network:
    driver: bridge