version: '3.8'

services:
  api:
    container_name: wshop_api_store
    build:
      context: ./docker
      dockerfile: ./Dockerfile
    ports:
      - ${API_PORT}:80
    volumes:
      - ./wshop-api-store:/var/www/wshop-api-store
    working_dir: /var/www/wshop-api-store
    networks:
      - api_network

  mysql:
    image: mysql:latest
    container_name: wshop_api_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_api_data:/var/lib/mysql
      - ./docker/db/mysql:/docker-entrypoint-initdb.d
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - api_network

volumes:
  mysql_api_data:
    driver: local

networks:
  api_network:
    driver: bridge