version: '3.8'

services:
  web:
    container_name: wshop_web
    build:
      context: ./docker
      dockerfile: ./Dockerfile
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ./wshop-test:/var/www/wshop-test
    working_dir: /var/www/wshop-test
    networks:
      - app_network

  mysql:
    image: mysql:latest
    container_name: wshop_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./wshop-test/importSql.sql:/docker-entrypoint-initdb.d/importSql.sql
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - app_network

volumes:
  mysql_data:
    driver: local

networks:
  app_network:
    driver: bridge